# Generated by Django 2.1.7 on 2019-02-25 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_text', models.TextField(max_length=2000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('posted_by', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_title', models.CharField(max_length=100)),
                ('question_text', models.TextField(max_length=2000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('posted_by', models.TextField(max_length=50)),
                ('slug', models.SlugField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
